# clone tmp:
## git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# List of plugins
# Key bindings
# prefix + I :j Installs new plugins from GitHub or any other git repository
# prefix + U updates plugin(s)
# prefix + alt + u remove/uninstall plugins not on the plugin list

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @continuum-restore 'on'

set -g @plugin 'wfxr/tmux-power'
set -g @tmux_power_theme 'snow'

set -s escape-time 0
unbind C-b
set -g prefix C-Space
bind-key C-Space send-prefix

bind S command-prompt -p "New Session:" "new-session -A -s '%%'"
bind K confirm kill-session

bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"

bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# change statusbar color
# set status-utf8 on
# set utf8 on
set -g default-terminal "screen-256color"
# set -g status-bg black
# set -g status-fg white

run '~/.tmux/plugins/tpm/tpm'
