# List of plugins
# Key bindings
# prefix + I :j Installs new plugins from GitHub or any other git repository
# prefix + U updates plugin(s)
# prefix + alt + u remove/uninstall plugins not on the plugin list

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'


set -s escape-time 0
set -g @continuum-restore 'on'
unbind C-b
set -g prefix C-Space
bind-key C-Space send-prefix

bind S command-prompt -p "New Session:" "new-session -A -s '%%'"
bind K confirm kill-session

# change statusbar color
# set status-utf8 on
# set utf8 on
set -g default-terminal "screen-256color"
set -g status-bg black
set -g status-fg white

# bind-key -r G run-shell "~/.local/bin/tmux-sessionizer ~/workspace/calculadora"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
