-- local null_ls = require("null-ls")
--
-- -- local augroup = vim.api.nvim_create_augroup("LspFormatting", {})
--
-- null_ls.setup({
-- 	-- on_init = function(new_client, _)
-- 	-- 	new_client.offset_encoding = 'utf-8'
-- 	-- end,
-- 	sources = {
-- 		null_ls.builtins.formatting.stylua,
-- 		null_ls.builtins.formatting.prettierd,
-- 		-- null_ls.builtins.completion.spell,
-- 		null_ls.builtins.formatting.black,
-- 	},
-- 	offset_encoding = "utf-8",
--
-- 	-- on_attach = function(client, bufnr)
-- 	-- 	if client.supports_method("textDocument/formatting") then
-- 	-- 		vim.api.nvim_clear_autocmds({
-- 	-- 			group = augroup,
-- 	-- 			buffer = bufnr
-- 	-- 		})
-- 	-- 		vim.api.nvim_create_autocmd("BufWritePre", {
-- 	-- 			group = augroup,
-- 	-- 			buffer = bufnr,
-- 	-- 			callback = function()
-- 	-- 				vim.lsp.buf.format({bufnr = bufnr})
-- 	-- 			end
-- 	-- 		})
-- 	-- 	end
-- 	-- end
-- })
